
services:

  serve:
    build: ./Dockerfile
    image: sshtest
    ports:
      - "8080:8080"
      - "8070:8070"
    command: ["pfsv", "-c", "/config/docker.yaml"]
    volumes:
      - id_keys:/srv/keys
      - sqlite:/srv/db
      - buckets:/srv/store
volumes:
  id_keys:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/tom/workspace/go/sshtest/tmp/keys
  sqlite:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/tom/workspace/go/sshtest/tmp/db
  buckets:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/tom/workspace/go/sshtest/tmp/bucket