
FROM golang:1.18.0-alpine3.15 AS builder

RUN apk add --no-cache build-base gcc make openssh-keygen

ADD . /src

WORKDIR /src

RUN make build
RUN ssh-keygen -t ed25519 -f /tmp/id_host -C "autogenerated host key" -q -N ""
RUN ls /tmp

FROM alpine:3.15

COPY --from=builder /src/bin/pfsv /bin/pfsv
COPY --from=builder /tmp/id_host /srv/id_host
COPY --from=builder /tmp/id_host.pub /srv/id_host.pub

ADD ./config /config

