
NOCHECK=-o StrictHostKeyCheck=no
BUILDFLAGS=-buildvcs=false

.PHONY: tidy
tidy:
	go mod tidy

.PHONY: build
build:
	go build $(BUILDFLAGS) -v -o bin/pfsv ./cmd

.PHONY: run
run:
	go run $(BUILDFLAGS) ./cmd

.PHONY: folders
folders:
	mkdir --parents tmp/bucket tmp/db tmp/keys

.PHONY: keys
keys:
	ssh-keygen -t ed25519 -f /tmp/ssh/id_foo_ed25519 -C "autogenerated connection key" -q -N ""
	ssh-keygen -t ed25519 -f  /tmp/ssh/id_ed25519 -C "autogenerated client key" -q -N ""
