
NOCHECK=-o StrictHostKeyCheck=no
BUILDFLAGS=-buildvcs=false

.PHONY: tidy
tidy:
	go mod tidy

.PHONY: build
build:
	go build $(BUILDFLAGS) -v -o bin/pfsv ./cmd

.PHONY: folders
folders:
	mkdir --parents tmp/bucket tmp/db tmp/keys

.PHONY: keys
keys:
	ssh-keygen -t ed25591 -f ./tmp/keys/id_ed25591 -C "autogenerated connection key" -q -N ""
