app:
  filePath: /srv/store/
  host: 0.0.0.0
  dbFile: /srv/db/sql.db
  authorizedKeys:
    - "/srv/keys/id_ed25519.pub"
  hostKeys:
    - "/srv/id_host"
  manage:
    port: 8070
    defaultKeyLife: 24h
  serve:
    port: 8080
meta:
  version: 0.0.0
