app:
  filePath: /tmp/srv/
  host: 0.0.0.0
  dbFile: /tmp/tmp.db
  authorizedKeys:
    - "/tmp/ssh/id_ed25519.pub"
  hostKeys:
    - "/tmp/ssh/id_foo"
  manage:
    port: 8070
    defaultKeyLife: 24h
  serve:
    port: 8080
meta:
  version: 0.0.0
