app:
  filePath: /tmp/srv
  host: 0.0.0.0
  redisPort: 9999
  authorizedKeys:
    - "/tmp/ssh/id_ed25519.pub"
    - "~/.ssh/id_ed25519.pub"
  hostKeys:
    - "/tmp/ssh/id_foo"
  upload:
    port: 8070
    buckets:
      - pics
      - docs
      - backup
  serve:
    port: 8080
  manage: 
    port: 8060
    maxKeys: 10
    defaultKeyLife: 24h